---
# tasks file for roles/prometheus_deploy
- name: create the directory for prometheus
  file:
    path: /etc/prometheus
    state: directory
- name: get the prometheus base image
  shell: wget "{{ prometheus_release }}" -O /etc/prometheus/prometheus.tar.gz
- name: unzip the archive
  shell: tar -xf /etc/prometheus/prometheus.tar.gz -C /etc/prometheus/ --strip-components=1
- name: copy prometheus
  shell: mv /etc/prometheus/prometheus /usr/local/bin/ && mv /etc/prometheus/promtool /usr/local/bin/
- name: remove the archive
  shell: rm /etc/prometheus/prometheus.tar.gz
- name: copy the service file
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
- name: start prometheus
  systemd:
    name: prometheus
    daemon-reload: yes
    state: started