---
# tasks file for roles/prometheus_deploy
- name: create the directory for prometheus
  file:
    path: /etc/prometheus
    state: directory
- name: get the prometheus base image
  shell: wget "{{ prometheus_release }}" -O /etc/prometheus/prometheus.tar.gz
- name: unzip the archive
  shell: tar -xf /etc/prometheus/prometheus.tar.gz -C /etc/prometheus/ --strip-components=1
- name: copy prometheus
  copy:
    content: /etc/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    mode: +x
- name: copy promtool
  copy:
    content: /etc/prometheus/promtool
    dest: /usr/local/bin/promtool
    mode: +x
- name: remove the archive
  shell: rm /etc/prometheus/prometheus.tar.gz
- name: copy the service file
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
- name: start prometheus
  systemd:
    name: prometheus
    daemon-reload: yes
    state: started
- name: check if prometheus is up
  shell: systemctl status prometheus.service
  notify:
  - Enable Prometheus